link:
  raw: "https://discord.gg/donutsmp"
  display: "discord.gg/donutsmp"

message:
  discord:
    enabled: true
    lines:
      - "&r&#00A4FCᴊᴏɪɴ ᴛʜᴇ ᴅᴏɴᴜᴛꜱᴍᴘ ᴅɪꜱᴄᴏʀᴅ ᴄᴏᴍᴍᴜɴɪᴛʏ!"
      - "&#00A4FC&l•&r &f&n%link_display%"
    hover:
      - "&#00A4FCOpen the Discord invite"

  actionbar:
    enabled: true
    text: "&7The Link has been sent in chat!"

  reload:
    enabled: true
    lines:
      - "&#00A4FC&l•&r &f&nReloaded the config!"

sounds:
  pling:
    enabled: true
    sound: BLOCK_NOTE_BLOCK_PLING
    volume: 0.5
    pitch: 1.0

placeholderapi:
  enabled: true
